<?php
    echo "<h3>Test Site</h3>";
    $htmlOut = '
        <hr>
        <p>Dev Site Test Page</p>
        <a href="tmp.php?p=1">test 1 (printing session value)</a> <br/>
        <a href="http://127.0.0.1:8080/destroy.html?xsession=true">test 2 (kill session)</a><br/>';
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>